### ISSUE TITLE
Create and use a fetch utility.

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/monorepo#124]
Yes, I know. We can add another dependency.

However, I can write a really simple wrapper like the one I did in Doggo and we can use that just the same.

**Comment by booleans-oss** [comment]
The timing for this issue is on point:
Node just merged a PR adding the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) nativaly ([#41749](https://github.com/nodejs/node/pull/41749)).

I don't know when it is going to take effect, probably in the next couple of releases. But I think it's worth waiting for it
